version: '3.1'

services:
   db-choice:
        container_name: db-choice
        image: mariadb
        ports:
            - 3306:3306
        environment:
            MARIADB_DATABASE: choice
            MARIADB_ROOT_PASSWORD: mypass
        volumes:
            - './db-scripts/:/docker-entrypoint-initdb.d/'

   spring-boot-soap-ws:
        build: ./spring-boot-soap-ws
        container_name: spring-boot-soap-ws
        ports:
            - 8085:8080
        depends_on:
           - db-choice
        environment:
            CHOICE_DB_USERNAME: root
            CHOICE_DB_PASSWORD: mypass
            CHOICE_DB_HOST: 'db-choice'
            CHOICE_DB_PORT: 3306
            CHOICE_DB_NAME: choice